version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongodb-card
    restart: always
    ports:
      - "27024:27017"
    environment:
      MONGO_INITDB_DATABASE: carddb
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: