server:
  port: 8081
spring:
  application:
    name: customer-service
  data:
    mongodb:
      database: customerdb
      uri: mongodb://localhost:27021/customerdb
management.endpoints.web.exposure.include: "*"
springdoc:
  swagger-ui:
    path: /swagger