spring:
  application:
    name: customer-service
  config:
    import: "configserver:http://localhost:8888"
  data:
    mongodb:
      database: customerdb
management.endpoints.web.exposure.include: "*"
springdoc:
  swagger-ui:
    path: /swagger