version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongodb-debitcard
    restart: always
    ports:
      - "27025:27017"
    environment:
      MONGO_INITDB_DATABASE: debitcarddb
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: