spring:
  application:
    name: account-service
  config:
    import: "configserver:http://localhost:8888"
  data:
    mongodb:
      database: accountdb
management.endpoints.web.exposure.include: "*"
springdoc:
  swagger-ui:
    path: /swagger
card:
  service:
    base-url: http://localhost:8084

credit:
  service:
    base-url: http://credit-service:8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/