spring:
  application:
    name: debit-card-service
  config:
    import: "configserver:http://localhost:8888"
management.endpoints.web.exposure.include: "*"
springdoc:
  swagger-ui:
    path: /swagger
account:
  service:
    base-url: http://account-service:8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/