server:
  port: 8084
spring:
  application:
    name: card-service
  data:
    mongodb:
      database: carddb
      uri: mongodb://localhost:27024/carddb
management.endpoints.web.exposure.include: "*"
springdoc:
  swagger-ui:
    path: /swagger