spring:
  application:
    name: card-service
  config:
    import: "configserver:http://localhost:8888"
  data:
    mongodb:
      database: carddb
management.endpoints.web.exposure.include: "*"
springdoc:
  swagger-ui:
    path: /swagger
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/